# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShouldiGo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShouldiGo
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 5.0'
  target 'ShouldiGoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShouldiGoUITests' do
    # Pods for testing
  end

end
